version: 2

builds:
  - main: ./cmd/chat
    id: ai-chat
    binary: ai-chat
    env:
      - CGO_ENABLED=1
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64

archives:
  - format: tar.gz
    name_template: "ai-chat_{{ .Os }}_{{ .Arch }}"

changelog:
  sort: asc
